---
title: "typst-to-div Example"
format: typst
filters:
  - typst-to-div
typst-block-prefix: tb
typst-inline-prefix: ti
---


The standard way to run `.qmd` content through custom typst styling appears to 
be to wrap said content in typst blocks, e.g.

```{=typst}
#block(
    fill:luma(230), 
    inset:16pt,
    outset:-8pt, 
    radius:4pt,
    [
```

...quarto content...

```{=typst}
    ]   
) 
```

This lua filter allows users to create typst functions in a `typst-template.typ`
file (or just the `.qmd`) and call them from a Quarto div:

```{=typst}

#let myblock(text) = block(text,
    fill:luma(230), 
    inset:16pt,
    outset:-8pt, 
    radius:4pt
  )

#let mytext(body) = text(red)[#body]
```

:::{.tb-myblock}
...quarto content...
:::

There is also support for inline styling. Simply declare a function and call it 
inline via [spans]{.ti-mytext}.

Note that the div and span classes are identified by a user-defined prefix set in 
the document YAML. In this example, div classes are identified with a `tb-` 
prefix and span classes are identified with a `ti-` prefix. Hence, to call the typst 
block function `myblock` I used a div with class `.tb-myblock`, and to call the
the typst function `mytext` for inline styling I used the span class `.ti-mytext`. 
